type: google.api.Service
config_version: 3
name: test.googleapis.com
title: Client Libraries Showcase API

apis:
- name: testing.publishingsettings.OriginalServiceName
- name: testing.publishingsettings.ServiceWithHandwrittenSignatures
- name: testing.publishingsettings.ServiceWithResources

publishing:
  method_settings:
  - selector: testing.publishingsettings.ServiceWithMethodSettings.UnaryAutoPopulated
    auto_populated_fields:
    - request_id
  - selector: testing.publishingsettings.ServiceWithMethodSettings.ServerStreamingAutoPopulated
    auto_populated_fields:
    - request_id
  - selector: testing.publishingsettings.ServiceWithMethodSettings.ClientStreamingAutoPopulated
    auto_populated_fields:
    - request_id
  - selector: testing.publishingsettings.ServiceWithMethodSettings.BidiStreamingAutoPopulated
    auto_populated_fields:
    - request_id
  - selector: testing.publishingsettings.ServiceWithMethodSettings.LroAutoPopulated
    auto_populated_fields:
    - request_id
  - selector: testing.publishingsettings.ServiceWithMethodSettings.PaginatedAutoPopulated
    auto_populated_fields:
    - request_id
  librarySettings:
  - version: testing.publishingsettings.wrong1
  - version: testing.publishingsettings
    dotnetSettings:
      ignored_resources:
      - test.googleapis.com/Location
      renamed_resources:
        test.googleapis.com/OriginalDatabase: RenamedDatabase
      handwritten_signatures:
      - "ServiceWithHandwrittenSignatures.AMethod(string_1)"
      renamed_services:
        OriginalServiceName: RenamedServiceName
  - version: testing.publishingsettings.wrong2
