// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/api/field_behavior.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Api {

  /// <summary>Holder for reflection information generated from google/api/field_behavior.proto</summary>
  public static partial class FieldBehaviorReflection {

    #region Descriptor
    /// <summary>File descriptor for google/api/field_behavior.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FieldBehaviorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9nb29nbGUvYXBpL2ZpZWxkX2JlaGF2aW9yLnByb3RvEgpnb29nbGUuYXBp",
            "KnsKDUZpZWxkQmVoYXZpb3ISHgoaRklFTERfQkVIQVZJT1JfVU5TUEVDSUZJ",
            "RUQQABIMCghPUFRJT05BTBABEgwKCFJFUVVJUkVEEAISDwoLT1VUUFVUX09O",
            "TFkQAxIOCgpJTlBVVF9PTkxZEAQSDQoJSU1NVVRBQkxFEAVCcAoOY29tLmdv",
            "b2dsZS5hcGlCEkZpZWxkQmVoYXZpb3JQcm90b1ABWkFnb29nbGUuZ29sYW5n",
            "Lm9yZy9nZW5wcm90by9nb29nbGVhcGlzL2FwaS9hbm5vdGF0aW9uczthbm5v",
            "dGF0aW9uc6ICBEdBUEliBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Google.Api.FieldBehavior), }, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// An indicator of the behavior of a given field (for example, that a field
  /// is required in requests, or given as output but ignored as input).
  /// This DOES NOT change the behavior in protocol buffers itself; it only
  /// denotes the behavior and may affect how API tooling handles the field.
  /// </summary>
  public enum FieldBehavior {
    [pbr::OriginalName("FIELD_BEHAVIOR_UNSPECIFIED")] Unspecified = 0,
    /// <summary>
    /// Specifically denotes a field as optional.
    /// Because fields are optional by default, this annotation is unnecessary;
    /// however, it may be provided if doing so is useful for humans reading
    /// the file.
    /// </summary>
    [pbr::OriginalName("OPTIONAL")] Optional = 1,
    /// <summary>
    /// Denotes a field as required.
    /// This indicates that the field *must* be provided as part of the request,
    /// and failure to do so will cause an error (usually `INVALID_ARGUMENT`).
    /// </summary>
    [pbr::OriginalName("REQUIRED")] Required = 2,
    /// <summary>
    /// Denotes a field as output only.
    /// This indicates that the field is provided in responses, but including the
    /// field in a request does nothing (the server *must* ignore it and
    /// *must not* throw an error as a result of the field's presence).
    /// </summary>
    [pbr::OriginalName("OUTPUT_ONLY")] OutputOnly = 3,
    /// <summary>
    /// Denotes a field as input only.
    /// This indicates that the field is provided in requests, and the
    /// corresponding field is not included in output.
    /// </summary>
    [pbr::OriginalName("INPUT_ONLY")] InputOnly = 4,
    /// <summary>
    /// Denotes a field as immutable.
    /// This indicates that the field may be set once in a request to create a
    /// resource, but may not be changed thereafter.
    /// </summary>
    [pbr::OriginalName("IMMUTABLE")] Immutable = 5,
  }

  #endregion

}

#endregion Designer generated code
