// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/api/resource.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.Api {

  /// <summary>Holder for reflection information generated from google/api/resource.proto</summary>
  public static partial class ResourceReflection {

    #region Descriptor
    /// <summary>File descriptor for google/api/resource.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ResourceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chlnb29nbGUvYXBpL3Jlc291cmNlLnByb3RvEgpnb29nbGUuYXBpGiBnb29n",
            "bGUvcHJvdG9idWYvZGVzY3JpcHRvci5wcm90byIrCghSZXNvdXJjZRIPCgdw",
            "YXR0ZXJuGAEgASgJEg4KBnN5bWJvbBgCIAEoCSJjCgtSZXNvdXJjZVNldBIO",
            "CgZzeW1ib2wYASABKAkSJwoJcmVzb3VyY2VzGAIgAygLMhQuZ29vZ2xlLmFw",
            "aS5SZXNvdXJjZRIbChNyZXNvdXJjZV9yZWZlcmVuY2VzGAMgAygJOkYKCHJl",
            "c291cmNlEh0uZ29vZ2xlLnByb3RvYnVmLkZpZWxkT3B0aW9ucxidCCABKAsy",
            "FC5nb29nbGUuYXBpLlJlc291cmNlOk0KDHJlc291cmNlX3NldBIdLmdvb2ds",
            "ZS5wcm90b2J1Zi5GaWVsZE9wdGlvbnMYngggASgLMhcuZ29vZ2xlLmFwaS5S",
            "ZXNvdXJjZVNldDo6ChJyZXNvdXJjZV9yZWZlcmVuY2USHS5nb29nbGUucHJv",
            "dG9idWYuRmllbGRPcHRpb25zGJ8IIAEoCTpQChNyZXNvdXJjZV9kZWZpbml0",
            "aW9uEhwuZ29vZ2xlLnByb3RvYnVmLkZpbGVPcHRpb25zGJ0IIAMoCzIULmdv",
            "b2dsZS5hcGkuUmVzb3VyY2VCugEKDmNvbS5nb29nbGUuYXBpQg1SZXNvdXJj",
            "ZVByb3RvUAFaQWdvb2dsZS5nb2xhbmcub3JnL2dlbnByb3RvL2dvb2dsZWFw",
            "aXMvYXBpL2Fubm90YXRpb25zO2Fubm90YXRpb25zogIER0FQSepBHQoScHJv",
            "amVjdHMve3Byb2plY3R9EgdQcm9qZWN06kEsChxvcmdhbml6YXRpb25zL3tv",
            "cmdhbml6YXRpb259EgxPcmdhbml6YXRpb25iBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { pbr::FileDescriptor.DescriptorProtoFileDescriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.Resource), global::Google.Api.Resource.Parser, new[]{ "Pattern", "Symbol" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.Api.ResourceSet), global::Google.Api.ResourceSet.Parser, new[]{ "Symbol", "Resources", "ResourceReferences" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// An annotation designating that this field designates a One Platform
  /// resource.
  ///
  /// Example:
  ///
  ///     message Topic {
  ///       string name = 1 [(google.api.resource) = {
  ///         name: "projects/{project}/topics/{topic}"
  ///       }];
  ///     }
  /// </summary>
  public sealed partial class Resource : pb::IMessage<Resource> {
    private static readonly pb::MessageParser<Resource> _parser = new pb::MessageParser<Resource>(() => new Resource());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Resource> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.ResourceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource(Resource other) : this() {
      pattern_ = other.pattern_;
      symbol_ = other.symbol_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Resource Clone() {
      return new Resource(this);
    }

    /// <summary>Field number for the "pattern" field.</summary>
    public const int PatternFieldNumber = 1;
    private string pattern_ = "";
    /// <summary>
    /// Required. The resource's name template.
    ///
    /// Examples:
    ///   - "projects/{project}/topics/{topic}"
    ///   - "projects/{project}/knowledgeBases/{knowledge_base}"
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Pattern {
      get { return pattern_; }
      set {
        pattern_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 2;
    private string symbol_ = "";
    /// <summary>
    /// The name that should be used in code to describe the resource,
    /// in PascalCase.
    ///
    /// If omitted, this is inferred from the name of the message.
    /// This is required if the resource is being defined without the context
    /// of a message (see `resource_definition`, below).
    ///
    /// Example:
    ///   option (google.api.resource_definition) = {
    ///     pattern: "projects/{project}"
    ///     symbol: "Project"
    ///   };
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Resource);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Resource other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Pattern != other.Pattern) return false;
      if (Symbol != other.Symbol) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Pattern.Length != 0) hash ^= Pattern.GetHashCode();
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Pattern.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Pattern);
      }
      if (Symbol.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Symbol);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Pattern.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Pattern);
      }
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Resource other) {
      if (other == null) {
        return;
      }
      if (other.Pattern.Length != 0) {
        Pattern = other.Pattern;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Pattern = input.ReadString();
            break;
          }
          case 18: {
            Symbol = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// An annotation designating that this field designates a set of One Platform
  /// resources.
  /// </summary>
  public sealed partial class ResourceSet : pb::IMessage<ResourceSet> {
    private static readonly pb::MessageParser<ResourceSet> _parser = new pb::MessageParser<ResourceSet>(() => new ResourceSet());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ResourceSet> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Google.Api.ResourceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceSet() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceSet(ResourceSet other) : this() {
      symbol_ = other.symbol_;
      resources_ = other.resources_.Clone();
      resourceReferences_ = other.resourceReferences_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ResourceSet Clone() {
      return new ResourceSet(this);
    }

    /// <summary>Field number for the "symbol" field.</summary>
    public const int SymbolFieldNumber = 1;
    private string symbol_ = "";
    /// <summary>
    /// The colloquial name of the resource.
    /// If omitted, this is the name of the message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Symbol {
      get { return symbol_; }
      set {
        symbol_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "resources" field.</summary>
    public const int ResourcesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Google.Api.Resource> _repeated_resources_codec
        = pb::FieldCodec.ForMessage(18, global::Google.Api.Resource.Parser);
    private readonly pbc::RepeatedField<global::Google.Api.Resource> resources_ = new pbc::RepeatedField<global::Google.Api.Resource>();
    /// <summary>
    /// Component resources that are part of the set.
    /// Resources declared within a resource set must have `name` set.
    ///
    /// The final set of resources in the resource set is the union of
    /// `resources` and `resource_references`.
    ///
    /// Resources defined here are only scoped within the parent ResourceSet;
    /// i.e. other messages cannot reference these contained Resources by name.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Google.Api.Resource> Resources {
      get { return resources_; }
    }

    /// <summary>Field number for the "resource_references" field.</summary>
    public const int ResourceReferencesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_resourceReferences_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> resourceReferences_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// References to existing resources (messages of resource definitions)
    /// that are part of the set.
    ///
    /// These may be specified as fully-qualified (e.g. "google.pubsub.v1.Topic")
    /// or just the resource/proto name if it is defined within the same package.
    ///
    /// The final set of resources in the resource set is the union of
    /// `resources` and `resource_references`.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> ResourceReferences {
      get { return resourceReferences_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ResourceSet);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ResourceSet other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Symbol != other.Symbol) return false;
      if(!resources_.Equals(other.resources_)) return false;
      if(!resourceReferences_.Equals(other.resourceReferences_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Symbol.Length != 0) hash ^= Symbol.GetHashCode();
      hash ^= resources_.GetHashCode();
      hash ^= resourceReferences_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Symbol.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Symbol);
      }
      resources_.WriteTo(output, _repeated_resources_codec);
      resourceReferences_.WriteTo(output, _repeated_resourceReferences_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Symbol.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Symbol);
      }
      size += resources_.CalculateSize(_repeated_resources_codec);
      size += resourceReferences_.CalculateSize(_repeated_resourceReferences_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ResourceSet other) {
      if (other == null) {
        return;
      }
      if (other.Symbol.Length != 0) {
        Symbol = other.Symbol;
      }
      resources_.Add(other.resources_);
      resourceReferences_.Add(other.resourceReferences_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Symbol = input.ReadString();
            break;
          }
          case 18: {
            resources_.AddEntriesFrom(input, _repeated_resources_codec);
            break;
          }
          case 26: {
            resourceReferences_.AddEntriesFrom(input, _repeated_resourceReferences_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
