type: google.api.Service
config_version: 3
name: test.googleapis.com
title: Client Libraries Showcase API

apis:
- name: testing.lro.Lro

publishing:
  method_settings:
  - selector: testing.lro.Lro.ServiceConfigPollingMethod
    long_running:
      initial_poll_delay: 60s
      poll_delay_multiplier: 2
      max_poll_delay: 360s
      total_poll_timeout: 54000s
