// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: google/longrunning/operations.proto
// </auto-generated>

// This file has been edited to only include the extra `OperationInfo` class.
// When the Google.LongRunning package has been updated, this project will not be required.

#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Google.LongRunning {

  /// <summary>Holder for reflection information generated from google/longrunning/operations.proto</summary>
  public static partial class OperationsReflection {

    #region Descriptor
    /// <summary>File descriptor for google/longrunning/operations.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OperationsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNnb29nbGUvbG9uZ3J1bm5pbmcvb3BlcmF0aW9ucy5wcm90bxISZ29vZ2xl",
            "LmxvbmdydW5uaW5nGhxnb29nbGUvYXBpL2Fubm90YXRpb25zLnByb3RvGhln",
            "b29nbGUvcHJvdG9idWYvYW55LnByb3RvGiBnb29nbGUvcHJvdG9idWYvZGVz",
            "Y3JpcHRvci5wcm90bxobZ29vZ2xlL3Byb3RvYnVmL2VtcHR5LnByb3RvGhdn",
            "b29nbGUvcnBjL3N0YXR1cy5wcm90byKoAQoJT3BlcmF0aW9uEgwKBG5hbWUY",
            "ASABKAkSJgoIbWV0YWRhdGEYAiABKAsyFC5nb29nbGUucHJvdG9idWYuQW55",
            "EgwKBGRvbmUYAyABKAgSIwoFZXJyb3IYBCABKAsyEi5nb29nbGUucnBjLlN0",
            "YXR1c0gAEigKCHJlc3BvbnNlGAUgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFu",
            "eUgAQggKBnJlc3VsdCIjChNHZXRPcGVyYXRpb25SZXF1ZXN0EgwKBG5hbWUY",
            "ASABKAkiXAoVTGlzdE9wZXJhdGlvbnNSZXF1ZXN0EgwKBG5hbWUYBCABKAkS",
            "DgoGZmlsdGVyGAEgASgJEhEKCXBhZ2Vfc2l6ZRgCIAEoBRISCgpwYWdlX3Rv",
            "a2VuGAMgASgJImQKFkxpc3RPcGVyYXRpb25zUmVzcG9uc2USMQoKb3BlcmF0",
            "aW9ucxgBIAMoCzIdLmdvb2dsZS5sb25ncnVubmluZy5PcGVyYXRpb24SFwoP",
            "bmV4dF9wYWdlX3Rva2VuGAIgASgJIiYKFkNhbmNlbE9wZXJhdGlvblJlcXVl",
            "c3QSDAoEbmFtZRgBIAEoCSImChZEZWxldGVPcGVyYXRpb25SZXF1ZXN0EgwK",
            "BG5hbWUYASABKAkiPQoNT3BlcmF0aW9uSW5mbxIVCg1yZXNwb25zZV90eXBl",
            "GAEgASgJEhUKDW1ldGFkYXRhX3R5cGUYAiABKAkyjAQKCk9wZXJhdGlvbnMS",
            "hgEKDkxpc3RPcGVyYXRpb25zEikuZ29vZ2xlLmxvbmdydW5uaW5nLkxpc3RP",
            "cGVyYXRpb25zUmVxdWVzdBoqLmdvb2dsZS5sb25ncnVubmluZy5MaXN0T3Bl",
            "cmF0aW9uc1Jlc3BvbnNlIh2C0+STAhcSFS92MS97bmFtZT1vcGVyYXRpb25z",
            "fRJ4CgxHZXRPcGVyYXRpb24SJy5nb29nbGUubG9uZ3J1bm5pbmcuR2V0T3Bl",
            "cmF0aW9uUmVxdWVzdBodLmdvb2dsZS5sb25ncnVubmluZy5PcGVyYXRpb24i",
            "IILT5JMCGhIYL3YxL3tuYW1lPW9wZXJhdGlvbnMvKip9EncKD0RlbGV0ZU9w",
            "ZXJhdGlvbhIqLmdvb2dsZS5sb25ncnVubmluZy5EZWxldGVPcGVyYXRpb25S",
            "ZXF1ZXN0GhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5IiCC0+STAhoqGC92MS97",
            "bmFtZT1vcGVyYXRpb25zLyoqfRKBAQoPQ2FuY2VsT3BlcmF0aW9uEiouZ29v",
            "Z2xlLmxvbmdydW5uaW5nLkNhbmNlbE9wZXJhdGlvblJlcXVlc3QaFi5nb29n",
            "bGUucHJvdG9idWYuRW1wdHkiKoLT5JMCJCIfL3YxL3tuYW1lPW9wZXJhdGlv",
            "bnMvKip9OmNhbmNlbDoBKjpaCg5vcGVyYXRpb25faW5mbxIeLmdvb2dsZS5w",
            "cm90b2J1Zi5NZXRob2RPcHRpb25zGJkIIAEoCzIhLmdvb2dsZS5sb25ncnVu",
            "bmluZy5PcGVyYXRpb25JbmZvQpQBChZjb20uZ29vZ2xlLmxvbmdydW5uaW5n",
            "Qg9PcGVyYXRpb25zUHJvdG9QAVo9Z29vZ2xlLmdvbGFuZy5vcmcvZ2VucHJv",
            "dG8vZ29vZ2xlYXBpcy9sb25ncnVubmluZztsb25ncnVubmluZ6oCEkdvb2ds",
            "ZS5Mb25nUnVubmluZ8oCEkdvb2dsZVxMb25nUnVubmluZ2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.AnyReflection.Descriptor, pbr::FileDescriptor.DescriptorProtoFileDescriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Rpc.StatusReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.Operation), global::Google.LongRunning.Operation.Parser, new[]{ "Name", "Metadata", "Done", "Error", "Response" }, new[]{ "Result" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.GetOperationRequest), global::Google.LongRunning.GetOperationRequest.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.ListOperationsRequest), global::Google.LongRunning.ListOperationsRequest.Parser, new[]{ "Name", "Filter", "PageSize", "PageToken" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.ListOperationsResponse), global::Google.LongRunning.ListOperationsResponse.Parser, new[]{ "Operations", "NextPageToken" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.CancelOperationRequest), global::Google.LongRunning.CancelOperationRequest.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.DeleteOperationRequest), global::Google.LongRunning.DeleteOperationRequest.Parser, new[]{ "Name" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Google.LongRunning.OperationInfo), global::Google.LongRunning.OperationInfo.Parser, new[]{ "ResponseType", "MetadataType" }, null, null, null)
          }));
    }
    #endregion

  }
    #region Messages
    /// <summary>
    /// A message representing the message types used by a long-running operation.
    ///
    /// Example:
    ///
    ///   rpc LongRunningRecognize(LongRunningRecognizeRequest)
    ///       returns (google.longrunning.Operation) {
    ///     option (google.longrunning.operation_info) = {
    ///       response_type: "LongRunningRecognizeResponse"
    ///       metadata_type: "LongRunningRecognizeMetadata"
    ///     };
    ///   }
    /// </summary>
    public sealed partial class OperationInfo : pb::IMessage<OperationInfo> {
    private static readonly pb::MessageParser<OperationInfo> _parser = new pb::MessageParser<OperationInfo>(() => new OperationInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OperationInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
        get => throw new System.NotImplementedException();
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInfo(OperationInfo other) : this() {
      responseType_ = other.responseType_;
      metadataType_ = other.metadataType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OperationInfo Clone() {
      return new OperationInfo(this);
    }

    /// <summary>Field number for the "response_type" field.</summary>
    public const int ResponseTypeFieldNumber = 1;
    private string responseType_ = "";
    /// <summary>
    /// Required. The message name of the primary return type for this
    /// long-running operation.
    /// This type will be used to deserialize the LRO's response.
    ///
    /// If the response is in a different package from the rpc, a fully-qualified
    /// message name must be used (e.g. `google.protobuf.Struct`).
    ///
    /// Note: Altering this value constitutes a breaking change.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ResponseType {
      get { return responseType_; }
      set {
        responseType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "metadata_type" field.</summary>
    public const int MetadataTypeFieldNumber = 2;
    private string metadataType_ = "";
    /// <summary>
    /// Required. The message name of the metadata type for this long-running
    /// operation.
    ///
    /// If the response is in a different package from the rpc, a fully-qualified
    /// message name must be used (e.g. `google.protobuf.Struct`).
    ///
    /// Note: Altering this value constitutes a breaking change.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string MetadataType {
      get { return metadataType_; }
      set {
        metadataType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OperationInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OperationInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ResponseType != other.ResponseType) return false;
      if (MetadataType != other.MetadataType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ResponseType.Length != 0) hash ^= ResponseType.GetHashCode();
      if (MetadataType.Length != 0) hash ^= MetadataType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ResponseType.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ResponseType);
      }
      if (MetadataType.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MetadataType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ResponseType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ResponseType);
      }
      if (MetadataType.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MetadataType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OperationInfo other) {
      if (other == null) {
        return;
      }
      if (other.ResponseType.Length != 0) {
        ResponseType = other.ResponseType;
      }
      if (other.MetadataType.Length != 0) {
        MetadataType = other.MetadataType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ResponseType = input.ReadString();
            break;
          }
          case 18: {
            MetadataType = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
