using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Text;

namespace Google.Api.Generator.RoslynUtils
{
    internal static class Keywords
    {
        // Taken from: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/
        private static IImmutableSet<string> s_keywords = ImmutableHashSet.Create(
            "abstract",
            "as",
            "base",
            "bool",
            "break",
            "byte",
            "case",
            "catch",
            "char",
            "checked",
            "class",
            "const",
            "continue",
            "decimal",
            "default",
            "delegate",
            "do",
            "double",
            "else",
            "enum",
            "event",
            "explicit",
            "extern",
            "false",
            "finally",
            "fixed",
            "float",
            "for",
            "foreach",
            "goto",
            "if",
            "implicit",
            "in",
            "int",
            "interface",
            "internal",
            "is",
            "lock",
            "long",
            "namespace",
            "new",
            "null",
            "object",
            "operator",
            "out",
            "override",
            "params",
            "private",
            "protected",
            "public",
            "readonly",
            "ref",
            "return",
            "sbyte",
            "sealed",
            "short",
            "sizeof",
            "stackalloc",
            "static",
            "string",
            "struct",
            "switch",
            "this",
            "throw",
            "true",
            "try",
            "typeof",
            "uint",
            "ulong",
            "unchecked",
            "unsafe",
            "ushort",
            "using",
            "virtual",
            "void",
            "volatile",
            "while"
            );

        public static string PrependAtIfKeyword(string word) => s_keywords.Contains(word) ? $"@{word}" : word;
    }
}
