name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-18.04
    env:	
      DOTNET_NOLOGO: true

    steps:	
    - uses: actions/checkout@v2	
      with:	
        submodules: true	

    - name: Setup .NET Core 3.1	
      uses: actions/setup-dotnet@v1	
      with:	
        dotnet-version: 3.1.x

    - name: Build and test	
      run: |
        dotnet build
        dotnet test Google.Api.Generator.Tests --logger:"console;noprogress=true"
        dotnet test Google.Api.Generator.Rest.Tests --logger:"console;noprogress=true"
