name: Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    env:	
      DOTNET_NOLOGO: true

    steps:	
    - uses: actions/checkout@v5
      with:	
        submodules: true	

    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x

    - name: Build and test	
      run: |
        dotnet build
        dotnet test Google.Api.Generator.Tests --logger:"console;noprogress=true"
        dotnet test Google.Api.Generator.Rest.Tests --logger:"console;noprogress=true"
