name: Build
on: [push, pull_request]
permissions: {}
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      with:
        submodules: true
        persist-credentials: false

    - name: Setup .NET
      uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6
      with:
        dotnet-version: 8.0.x

    - name: Build and test
      run: |
        dotnet build
        dotnet test Google.Api.Generator.Tests --logger:"console;noprogress=true"
        dotnet test Google.Api.Generator.Rest.Tests --logger:"console;noprogress=true"
