// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Logging.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ResourceUpgradeTest {
  public static partial class LoggingServiceV2
  {
    static readonly string __ServiceName = "resourceupgradetest.LoggingServiceV2";

    static readonly grpc::Marshaller<global::ResourceUpgradeTest.DeleteLogRequest> __Marshaller_resourceupgradetest_DeleteLogRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.DeleteLogRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ResourceUpgradeTest.Empty> __Marshaller_resourceupgradetest_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ResourceUpgradeTest.ListLogsRequest> __Marshaller_resourceupgradetest_ListLogsRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.ListLogsRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ResourceUpgradeTest.ListLogsResponse> __Marshaller_resourceupgradetest_ListLogsResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.ListLogsResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::ResourceUpgradeTest.DeleteLogRequest, global::ResourceUpgradeTest.Empty> __Method_DeleteLog = new grpc::Method<global::ResourceUpgradeTest.DeleteLogRequest, global::ResourceUpgradeTest.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteLog",
        __Marshaller_resourceupgradetest_DeleteLogRequest,
        __Marshaller_resourceupgradetest_Empty);

    static readonly grpc::Method<global::ResourceUpgradeTest.ListLogsRequest, global::ResourceUpgradeTest.ListLogsResponse> __Method_ListLogs = new grpc::Method<global::ResourceUpgradeTest.ListLogsRequest, global::ResourceUpgradeTest.ListLogsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListLogs",
        __Marshaller_resourceupgradetest_ListLogsRequest,
        __Marshaller_resourceupgradetest_ListLogsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ResourceUpgradeTest.LoggingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of LoggingServiceV2</summary>
    public abstract partial class LoggingServiceV2Base
    {
      public virtual global::System.Threading.Tasks.Task<global::ResourceUpgradeTest.Empty> DeleteLog(global::ResourceUpgradeTest.DeleteLogRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::ResourceUpgradeTest.ListLogsResponse> ListLogs(global::ResourceUpgradeTest.ListLogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for LoggingServiceV2</summary>
    public partial class LoggingServiceV2Client : grpc::ClientBase<LoggingServiceV2Client>
    {
      /// <summary>Creates a new client for LoggingServiceV2</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public LoggingServiceV2Client(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for LoggingServiceV2 that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public LoggingServiceV2Client(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected LoggingServiceV2Client() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected LoggingServiceV2Client(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ResourceUpgradeTest.Empty DeleteLog(global::ResourceUpgradeTest.DeleteLogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteLog(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ResourceUpgradeTest.Empty DeleteLog(global::ResourceUpgradeTest.DeleteLogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteLog, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.Empty> DeleteLogAsync(global::ResourceUpgradeTest.DeleteLogRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteLogAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.Empty> DeleteLogAsync(global::ResourceUpgradeTest.DeleteLogRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteLog, null, options, request);
      }
      public virtual global::ResourceUpgradeTest.ListLogsResponse ListLogs(global::ResourceUpgradeTest.ListLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ResourceUpgradeTest.ListLogsResponse ListLogs(global::ResourceUpgradeTest.ListLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListLogs, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.ListLogsResponse> ListLogsAsync(global::ResourceUpgradeTest.ListLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.ListLogsResponse> ListLogsAsync(global::ResourceUpgradeTest.ListLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListLogs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override LoggingServiceV2Client NewInstance(ClientBaseConfiguration configuration)
      {
        return new LoggingServiceV2Client(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(LoggingServiceV2Base serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_DeleteLog, serviceImpl.DeleteLog)
          .AddMethod(__Method_ListLogs, serviceImpl.ListLogs).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LoggingServiceV2Base serviceImpl)
    {
      serviceBinder.AddMethod(__Method_DeleteLog, serviceImpl.DeleteLog);
      serviceBinder.AddMethod(__Method_ListLogs, serviceImpl.ListLogs);
    }

  }
}
#endregion
