// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ResourceOnly.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ResourceUpgradeTest {
  public static partial class Svc
  {
    static readonly string __ServiceName = "resourceupgradetest.Svc";

    static readonly grpc::Marshaller<global::ResourceUpgradeTest.Request> __Marshaller_resourceupgradetest_Request = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.Request.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ResourceUpgradeTest.Response> __Marshaller_resourceupgradetest_Response = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ResourceUpgradeTest.Response.Parser.ParseFrom);

    static readonly grpc::Method<global::ResourceUpgradeTest.Request, global::ResourceUpgradeTest.Response> __Method_M = new grpc::Method<global::ResourceUpgradeTest.Request, global::ResourceUpgradeTest.Response>(
        grpc::MethodType.Unary,
        __ServiceName,
        "M",
        __Marshaller_resourceupgradetest_Request,
        __Marshaller_resourceupgradetest_Response);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ResourceUpgradeTest.ResourceOnlyReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Svc</summary>
    public abstract partial class SvcBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ResourceUpgradeTest.Response> M(global::ResourceUpgradeTest.Request request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Svc</summary>
    public partial class SvcClient : grpc::ClientBase<SvcClient>
    {
      /// <summary>Creates a new client for Svc</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public SvcClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Svc that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public SvcClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected SvcClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected SvcClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ResourceUpgradeTest.Response M(global::ResourceUpgradeTest.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return M(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ResourceUpgradeTest.Response M(global::ResourceUpgradeTest.Request request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_M, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.Response> MAsync(global::ResourceUpgradeTest.Request request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return MAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ResourceUpgradeTest.Response> MAsync(global::ResourceUpgradeTest.Request request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_M, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override SvcClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new SvcClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(SvcBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_M, serviceImpl.M).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, SvcBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_M, serviceImpl.M);
    }

  }
}
#endregion
